version: '3.6'

services:
  db:
    image: mariadb
    ports:
      - 3336:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=test
      - TZ=Etc/GMT0
    expose:
      - 3336
